# Generated by Django 4.1 on 2024-09-21 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("approver", "0002_notification_rename_approvers_approver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
