# Generated by Django 4.1 on 2024-09-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approver", "0004_approver_username_task_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="file",
            field=models.FileField(default=2, upload_to="docs/"),
            preserve_default=False,
        ),
    ]
