# Generated by Django 4.1 on 2024-09-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approver", "0005_task_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="file",
            field=models.FileField(default=None, upload_to="docs/"),
        ),
    ]
