# Generated by Django 4.1 on 2024-09-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approver", "0006_alter_task_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approver",
            name="tasks",
        ),
        migrations.RemoveField(
            model_name="approver",
            name="username",
        ),
        migrations.AlterField(
            model_name="task",
            name="curr_approvals",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(default="Not Started", max_length=50),
        ),
    ]
