# Generated by Django 4.1 on 2024-09-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approver", "0007_remove_approver_tasks_remove_approver_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="filetype",
            field=models.CharField(default="application/pdf", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="approved",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="notification",
            name="curr_approvals",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(default="Not Started", max_length=50),
        ),
    ]
